#!/bin/bash

name=t$1-$2

cline="import mf_pari; print(mf_pari.Nspaces($1,$2));"
nspaces=`echo ${cline} | sagedev -q | head -1 | cut -d " " -f 2`
#echo $nspaces spaces to compute for $1..$2
ndone=`cat ${name}-* | wc -l`
#echo $ndone spaces done
echo $ndone / ${nspaces} spaces completed for $1..$2
echo `grep Exit sage.out-${name}-* | wc -l ` jobs have completed
echo `grep again sage.out-${name}-* | wc -l ` spaces failed
echo `grep again sage.out-${name}-* | cut -d " " -f 14`



