#!/bin/bash

Nk2min=$1
Nk2max=$2
filename=$3
dmax=$4
nan=$5
njobs=$6
let 'njobs1 = njobs - 1'

for jobno in `seq 0 ${njobs1}`; do

cline="import mf_pari; mf_pari.DecomposeSpaces(\"${filename}-${jobno}\",${Nk2min},${Nk2max},${dmax},${nan},${njobs},${jobno});"
echo ${cline}
echo ${cline} | sagedev -q  > sage.out-${filename}-${jobno} &
done




